/* global root */
"use strict";

function Pawn(args) {
	this.name = args.name;
	this.number = args.number;
	this.qty = args.qty;
	this.set = args.set;
	this.size = args.size;
	this.tags = (typeof args.tags === "string") ? args.tags.split(", ") : args.tags;
	this.sheet = args.sheet;

	this.pawnClass = (args.sheet === "0") ? [
		"pawn",
		args.size,
		"no-pawn-available",
	].join(" ") : [
		"pawn",
		args.size,
		"sheet" + args.sheet,
		"row" + args.row,
		"col" + args.col,
	].join(" ");

	for ( var i = 0; i < this.tags.length; i++ ) {
		root.add(this, this.tags[i]);
	}
}

var pawns = [];

function addPawn(s) {
	var matches = s.match(/^([^\t]+)\t(\d+)\t(small|medium|large|huge)\t(\d+)\t(\d+)\t(\d+)\t(\d+)\t([^\t]+)\t+((?:\w+:)*\w+(?:, (?:\w+:)*\w+)*)$/);
	if (!matches) {
		console.warn("Unable to interpolate:", s);
	} else {
		pawns.push(new Pawn({
			set:	matches[1],
			number:	matches[2],
			size:	matches[3],
			qty:	matches[4],
			sheet:	matches[5],
			row:	matches[6],
			col:	matches[7],
			name:	matches[8],
			tags:	matches[9],
		}));
	}
}

addPawn("BS1	1	small	1	12	4	1	Archon, Lantern	Type:Outsider:Good:Archon");
addPawn("BS1	2	small	4	12	4	2	Bat Swarm	Type:Animal:Flying:Bat, Misc:Swarm");
addPawn("BS1	3	small	1	12	2	4	Choker	Type:Undead:Corporeal:Ghoul");
addPawn("BS1	4	small	1	12	1	4	Cockatrice	Type:Beast:Bipedal");
addPawn("BS1	5	small	3	12	4	5	Dark Creeper	Type:Humanoid:Dwarf");
addPawn("BS1	6	small	1	12	3	6	Darkmantle	Type:Weird:Tentacles");
addPawn("BS1	7	small	2	13	4	1	Demon, Dretch	Type:Outsider:Evil");
addPawn("BS1	8	small	1	13	4	3	Demon, Quasit	Type:Outsider:Evil:Imp");
addPawn("BS1	9	small	2	13	4	4	Derro	Type:Humanoid:Gnome");
addPawn("BS1	10	small	1	13	2	4	Devil, Imp	Type:Outsider:Evil:Imp, Misc:Familiar");
addPawn("BS1	11	small	1	13	1	4	Dog	Type:Animal:Quadrupedal:Dog");
addPawn("BS1	12	small	1	13	4	5	Eagle	Type:Animal:Flying:Bird:Eagle");
addPawn("BS1	13	small	1	13	3	5	Electric Eel	Type:Animal:Aquatic:Eel, Environment:Aquatic");
addPawn("BS1	14	small	1	13	4	6	Elemental, Air	Type:Elemental:Air");
addPawn("BS1	15	small	1	13	3	6	Elemental, Earth	Type:Elemental:Earth");
addPawn("BS1	16	small	1	14	4	1	Elemental, Fire	Type:Elemental:Fire");
addPawn("BS1	17	small	1	14	4	2	Elemental, Water	Type:Elemental:Water");
addPawn("BS1	18	small	4	14	4	3	Goblin Warrior	Type:Humanoid:Goblin");
addPawn("BS1	19	small	1	14	1	4	Homunculus	Type:Outsider:Evil:Imp, Misc:Familiar");
addPawn("BS1	20	small	1	14	4	5	Intellect Devourer	Type:Undead:Corporeal:Piecemeal");
addPawn("BS1	21	small	1	15	4	1	Iron Cobra	Type:Animal:Snake");
addPawn("BS1	22	small	3	14	3	5	Kobold Warrior	Type:Humanoid:Kobold");
addPawn("BS1	23	small	2	15	4	2	Mephit	Type:Outsider:Evil:Imp, Misc:Familiar");
addPawn("BS1	24	small	2	15	4	4	Mite	Type:Humanoid:Misc");
addPawn("BS1	25	small	1	15	2	4	Pixie	Type:Fae:Pixie");
addPawn("BS1	26	small	1	15	1	4	Pseudodragon	Type:Dragon:Dragonkin");
addPawn("BS1	27	small	2	15	4	5	Rat, Dire	Type:Animal:Quadrupedal:Rat");
addPawn("BS1	28	small	1	15	4	6	Shocker Lizard	Type:Animal:Quadrupedal:Lizard");
addPawn("BS1	29	small	4	16	4	1	Spider Swarm	Type:Animal:Insect:Spider, Misc:Swarm");
addPawn("BS1	30	small	2	16	3	4	Stirge	Type:Animal:Insect:Mosquito");
addPawn("BS1	31	small	1	15	3	6	Svirfneblin	Type:Humanoid:Gnome:Svirfneblin");
addPawn("BS1	32	small	2	16	1	4	Vargouille	Type:Undead:Corporeal:Piecemeal");
addPawn("BS1	33	small	2	16	3	5	Vegepygmy	Type:Weird:Plant:Humanoid");
addPawn("BS1	34	small	1	16	3	6	Will-o'-Wisp	Type:Undead:Incorporeal:Ghost");
addPawn("BS1	35	medium	1	1	1	1	Aasimar Cleric	Type:Humanoid:Human, Misc:Class:Cleric");
addPawn("BS1	36	medium	1	1	1	2	Angel, Astral Deva	Type:Outsider:Good:Angel");
addPawn("BS1	37	medium	1	1	1	3	Animated Object	Type:Weird:Object");
addPawn("BS1	38	medium	3	1	1	4	Ant, Giant Soldier	Type:Animal:Insect:Ant");
addPawn("BS1	39	medium	2	1	2	1	Archon, Hound	Type:Outsider:Good:Archon, Type:Humanoid:Type:Animal:Quadrupedal:Dog");
addPawn("BS1	40	medium	1	1	2	3	Archon, Trumpet	Type:Outsider:Good:Archon, Type:Outsider:Good:Angel");
addPawn("BS1	41	medium	2	1	2	4	Azata, Bralani	Type:Humanoid:Elf");
addPawn("BS1	42	medium	1	1	2	6	Azata, Ghaele	Type:Humanoid:Human");
addPawn("BS1	43	medium	1	1	3	1	Barghest	Type:Beast:Quadrupedal");
addPawn("BS1	44	medium	1	1	3	2	Basidirond	Type:Weird:Plant");
addPawn("BS1	45	medium	2	1	3	3	Basilisk	Type:Animal:Quadrupedal:Lizard");
addPawn("BS1	46	medium	1	1	3	5	Boar	Type:Animal:Quadrupedal:Boar");
addPawn("BS1	47	medium	3	1	3	6	Boggard	Type:Humanoid:Type:Animal:Aquatic:Frog");
addPawn("BS1	48	medium	3	1	4	3	Bugbear	Type:Humanoid:Bugbear");
addPawn("BS1	49	medium	1	1	4	6	Cat, Leopard	Type:Animal:Quadrupedal:Cat:Leopard");
addPawn("BS1	50	medium	2	1	5	1	Cave Fisher	Type:Animal:Insect:Scorpion");
addPawn("BS1	51	medium	1	2	1	1	Centipede, Giant	Type:Animal:Insect:Centipede");
addPawn("BS1	52	medium	2	1	5	3	Crab, Giant	Type:Animal:Aquatic:Crab, Environment:Aquatic");
addPawn("BS1	53	medium	1	2	1	2	Dark Stalker	Type:Humanoid, Misc:Class:Rogue:Assassin");
addPawn("BS1	54	medium	2	2	1	3	Demon, Babau	Type:Outsider:Evil:Demon");
addPawn("BS1	55	medium	1	2	1	5	Demon, Nabasu	Type:Outsider:Evil:Demon");
addPawn("BS1	56	medium	1	2	1	6	Demon, Shadow	Type:Outsider:Evil:Demon");
addPawn("BS1	57	medium	1	2	2	1	Demon, Succubus	Type:Outsider:Evil:Demon");
addPawn("BS1	58	medium	2	2	2	2	Devil, Barbed	Type:Outsider:Evil:Devil");
addPawn("BS1	59	medium	2	2	2	4	Devil, Bearded	Type:Outsider:Evil:Devil");
addPawn("BS1	60	medium	2	2	2	6	Devil, Erinyes	Type:Outsider:Evil:Devil, Type:Outsider:Good:Angel");
addPawn("BS1	61	medium	3	2	3	2	Devil, Lemure	Type:Outsider:Evil:Devil, Type:Weird:Ooze");
addPawn("BS1	62	medium	2	2	3	5	Dinosaur, Deinonychus	Type:Animal:Bipedal:Dinosaur");
addPawn("BS1	63	medium	1	2	4	1	Dog, Riding	Type:Animal:Quadrupedal:Dog");
addPawn("BS1	64	medium	1	2	4	2	Doppelganger	Type:Undead:Corporeal:Zombie");
addPawn("BS1	65	medium	1	2	4	3	Dragon, Young Black	Type:Dragon:Black");
addPawn("BS1	66	medium	1	2	4	4	Dragon, Young Brass	Type:Dragon:Brass");
addPawn("BS1	67	medium	1	2	4	5	Dragon, Young Copper	Type:Dragon:Copper");
addPawn("BS1	68	medium	1	2	4	6	Dragon, Young White	Type:Dragon:White");
addPawn("BS1	69	medium	1	2	5	1	Drow Noble Cleric	Type:Humanoid:Elf:Drow");
addPawn("BS1	70	medium	3	2	5	2	Drow Warrior	Type:Humanoid:Elf:Drow");
addPawn("BS1	71	medium	1	3	1	1	Dryad	Type:Fae:Dryad");
addPawn("BS1	72	medium	2	3	1	2	Duergar	Type:Humanoid:Dwarf:Duergar");
addPawn("BS1	73	medium	1	3	1	4	Elemental, Air	Type:Elemental:Air");
addPawn("BS1	74	medium	1	3	1	5	Elemental, Earth	Type:Elemental:Earth");
addPawn("BS1	75	medium	1	3	1	6	Elemental, Fire	Type:Elemental:Fire");
addPawn("BS1	76	medium	1	3	2	1	Elemental, Water	Type:Elemental:Water");
addPawn("BS1	77	medium	1	3	2	2	Ettercap	Type:Humanoid:Type:Animal:Insect:Spider");
addPawn("BS1	78	medium	1	3	2	3	Frog, Giant	Type:Animal:Aquatic:Frog");
addPawn("BS1	79	medium	1	3	2	4	Gargoyle	Type:Weird:Gargoyle");
addPawn("BS1	80	medium	1	3	2	5	Genie, Janni	Type:Humanoid:Human, Misc:Class:Mage");
addPawn("BS1	81	medium	1	3	2	6	Ghost	Type:Undead:Incorporeal:Ghost");
addPawn("BS1	82	medium	3	3	3	1	Ghoul	Type:Undead:Corporeal:Ghoul");
addPawn("BS1	83	medium	1	3	3	4	Gibbering Mouther	Type:Weird:Aberration");
addPawn("BS1	84	medium	3	3	3	5	Gnoll	Type:Humanoid:Gnoll");
addPawn("BS1	85	medium	1	3	4	2	Goblin Dog	Type:Beast:Quadrupedal, Type:Animal:Quadrupedal:Dog");
addPawn("BS1	86	medium	1	3	4	3	Golem, Ice	Type:Golem:Ice");
addPawn("BS1	87	medium	1	3	4	4	Golem, Wood	Type:Golem:Wood");
addPawn("BS1	88	medium	1	3	4	5	Gray Ooze	Type:Weird:Ooze");
addPawn("BS1	89	medium	1	3	4	6	Green Hag	Type:Humanoid:Hag");
addPawn("BS1	90	medium	1	3	5	1	Half-Dragon, Dracolisk	Type:Dragon:Dragonkin");
addPawn("BS1	91	medium	3	3	5	2	Harpy	Type:Humanoid:Bird:Harpy, Type:Outsider:Evil");
addPawn("BS1	92	medium	2	4	1	1	Hell Hound	Type:Outsider:Evil, Type:Beast:Quadrupedal:Dog, Type:Elemental:Fire");
addPawn("BS1	93	medium	3	4	1	3	Hobgoblin Fighter	Type:Humanoid:Hobgoblin");
addPawn("BS1	94	medium	1	4	1	6	Hyena	Type:Animal:Quadrupedal:Dog:Hyena");
addPawn("BS1	95	medium	1	4	2	1	Invisible Stalker	Type:Elemental:Air");
addPawn("BS1	96	medium	1	4	2	2	Kyton	Type:Outsider:Evil:Devil");
addPawn("BS1	97	medium	1	4	2	3	Leech, Giant	Type:Animal:Insect:Leech");
addPawn("BS1	98	medium	1	4	2	4	Lich	Type:Undead:Corporeal:Skeleton:Lich");
addPawn("BS1	99	medium	3	4	2	5	Lizardfolk	Type:Humanoid:Reptillian:Lizardfolk");
addPawn("BS1	100	medium	1	4	3	2	Lycanthrope, Wererat	Type:Humanoid:Lycanthrope:Wererat");
addPawn("BS1	101	medium	1	4	3	3	Lycanthrope, Werewolf	Type:Humanoid:Lycanthrope:Werewolf");
addPawn("BS1	102	medium	1	4	3	4	Medusa	Type:Humanoid:Human, Type:Humanoid:Reptillian:Serpent");
addPawn("BS1	103	medium	1	4	3	5	Merfolk Warrior	Type:Humanoid:Merfolk, Environment:Aquatic");
addPawn("BS1	104	medium	1	4	3	6	Mimic	Type:Weird:Object, Type:Weird:Shapeshifter");
addPawn("BS1	105	medium	1	4	4	1	Mohrg	Type:Undead:Corporeal:Skeleton");
addPawn("BS1	106	medium	2	4	4	2	Morlock	Type:Outsider:Evil");
addPawn("BS1	107	medium	2	4	4	4	Mummy	Type:Undead:Corporeal:Zombie:Mummy");
addPawn("BS1	108	medium	1	4	4	6	Night Hag	Type:Humanoid:Hag");
addPawn("BS1	109	medium	1	4	5	1	Nymph	Type:Fae:Nymph");
addPawn("BS1	110	medium	3	4	5	2	Orc Warrior	Type:Humanoid:Orc");
addPawn("BS1	111	medium	1	5	1	1	Rakshasa	Type:Humanoid:Type:Animal:Quadrupedal:Cat");
addPawn("BS1	112	medium	1	5	1	2	Rust Monster	Type:Beast:Quadrupedal");
addPawn("BS1	113	medium	2	5	1	3	Sahuagin	Type:Humanoid:Type:Animal:Fish, Environment:Aquatic");
addPawn("BS1	114	medium	1	5	1	5	Salamander	Type:Humanoid:Reptillian:Serpent");
addPawn("BS1	115	medium	1	5	1	6	Satyr	Type:Fae:Satyr");
addPawn("BS1	116	medium	1	5	2	1	Sea Hag	Type:Humanoid:Hag, Environment:Aquatic");
addPawn("BS1	117	medium	1	5	2	2	Shadow	Type:Elemental:Shadow, Type:Undead:Incorporeal:Shade");
addPawn("BS1	118	medium	1	5	2	3	Skeletal Champion	Type:Undead:Corporeal:Skeleton");
addPawn("BS1	119	medium	3	5	2	4	Skeleton	Type:Undead:Corporeal:Skeleton");
addPawn("BS1	120	medium	2	5	3	1	Skum	Type:Humanoid:Type:Animal:Fish, Environment:Aquatic");
addPawn("BS1	121	medium	1	5	3	3	Snake, Venomous	Type:Animal:Snake");
addPawn("BS1	122	medium	1	5	3	4	Spectre	Type:Undead:Incorporeal:Ghost");
addPawn("BS1	123	medium	3	5	3	5	Spider, Giant	Type:Animal:Insect:Spider");
addPawn("BS1	124	medium	1	5	4	2	Tengu Rogue	Type:Humanoid:Type:Animal:Flying:Bird:Tengu, Misc:Class:Rogue");
addPawn("BS1	125	medium	1	5	4	3	Tiefling Rogue	Type:Humanoid:Tiefling");
addPawn("BS1	126	medium	2	5	4	4	Troglodyte	Type:Humanoid:Reptillian:Troglodyte");
addPawn("BS1	127	medium	1	5	4	6	Vampire Sorcerer	Type:Humanoid:Human, Misc:Class:Mage");
addPawn("BS1	128	medium	1	5	5	1	Violet Fungus	Type:Weird:Plant:Fungus");
addPawn("BS1	129	medium	1	5	5	2	Wight	Type:Undead:Corporeal:Zombie");
addPawn("BS1	130	medium	2	5	5	3	Wolf	Type:Animal:Quadrupedal:Dog:Wolf");
addPawn("BS1	131	medium	1	12	4	5	Worg	Type:Animal:Quadrupedal:Dog:Wolf");
addPawn("BS1	132	medium	1	12	4	6	Wraith	Type:Undead:Incorporeal:Shade");
addPawn("BS1	133	medium	1	13	4	5	Xill	Type:Outsider:Evil");
addPawn("BS1	134	medium	1	13	4	6	Xorn	Type:Weird:Aberration");
addPawn("BS1	135	medium	1	15	4	5	Yellow Musk Creeper	Type:Weird:Plant");
addPawn("BS1	136	medium	2	14	4	5	Yeth Hound	Type:Beast:Quadrupedal:Dog, Type:Animal:Quadrupedal:Dog");
addPawn("BS1	137	medium	3	15	4	6	Zombie	Type:Undead:Corporeal:Zombie");
addPawn("BS1	138	large	1	1	5	3	Angel, Planetar	Type:Outsider:Good:Angel");
addPawn("BS1	139	large	1	2	5	3	Angel, Solar	Type:Outsider:Good:Angel");
addPawn("BS1	140	large	1	3	5	3	Ankheg	Type:Beast:Insect");
addPawn("BS1	141	large	1	4	5	3	Ape, Dire	Type:Animal:Bipedal:Ape");
addPawn("BS1	142	large	1	5	5	3	Ape, Gorilla	Type:Animal:Bipedal:Ape");
addPawn("BS1	143	large	1	6	5	1	Assassin Vine	Type:Weird:Plant");
addPawn("BS1	144	large	1	6	4	1	Azata, Lillend	Type:Humanoid:Reptillian:Serpent, Type:Outsider:Good:Angel");
addPawn("BS1	145	large	1	6	3	1	Barghest, Greater	Type:Beast:Quadrupedal");
addPawn("BS1	146	large	1	6	2	1	Bat, Dire	Type:Animal:Flying:Bat, Misc:Swarm");
addPawn("BS1	147	large	1	6	1	1	Bear, Dire	Type:Animal:Quadrupedal:Bear");
addPawn("BS1	148	large	1	6	5	2	Centaur	Type:Humanoid:Centaur");
addPawn("BS1	149	large	1	6	4	2	Chimera	Type:Beast:Quadrupedal:Chimera");
addPawn("BS1	150	large	1	6	3	2	Chuul	Type:Weird:Aberration:Type:Humanoid:Aquatic, Environment:Aquatic");
addPawn("BS1	151	large	1	6	2	2	Cloaker	Type:Weird:Aberration");
addPawn("BS1	152	large	1	6	1	2	Couatl	Type:Outsider:Good:Couatl, Type:Beast:Serpent");
addPawn("BS1	153	large	1	6	5	3	Crocodile	Type:Animal:Aquatic:Crocodile, Environment:Aquatic");
addPawn("BS1	154	large	1	6	4	3	Cyclops	Type:Humanoid:Giant:Cyclops");
addPawn("BS1	155	large	1	6	3	3	Demon, Balor	Type:Outsider:Evil:Demon");
addPawn("BS1	156	large	1	6	2	3	Demon, Hezrou	Type:Outsider:Evil:Demon");
addPawn("BS1	157	large	1	6	1	3	Demon, Marilith	Type:Outsider:Evil:Demon, Type:Humanoid:Reptillian:Serpent");
addPawn("BS1	158	large	1	7	5	1	Demon, Vrock	Type:Outsider:Evil:Demon, Type:Humanoid:Type:Animal:Flying:Bird");
addPawn("BS1	159	large	1	7	4	1	Devil, Bone	Type:Outsider:Evil:Demon");
addPawn("BS1	160	large	1	7	3	1	Devil, Horned	Type:Outsider:Evil:Demon");
addPawn("BS1	161	large	1	7	2	1	Devil, Ice	Type:Outsider:Evil:Demon");
addPawn("BS1	162	large	1	7	1	1	Devil, Pit Fiend	Type:Outsider:Evil:Demon");
addPawn("BS1	163	large	1	7	5	2	Devourer	Type:Undead:Corporeal:Zombie");
addPawn("BS1	164	large	1	7	4	2	Dragon, Adult Black	Type:Dragon:Black");
addPawn("BS1	165	large	1	7	3	2	Dragon, Adult Brass	Type:Dragon:Brass");
addPawn("BS1	166	large	1	7	2	2	Dragon, Adult Copper	Type:Dragon:Copper");
addPawn("BS1	167	large	1	7	1	2	Dragon, Adult White	Type:Dragon:White");
addPawn("BS1	168	large	1	7	5	3	Dragon, Young Blue	Type:Dragon:Blue");
addPawn("BS1	169	large	1	7	4	3	Dragon, Young Bronze	Type:Dragon:Bronze");
addPawn("BS1	170	large	1	7	3	3	Dragon, Young Gold	Type:Dragon:Gold");
addPawn("BS1	171	large	1	7	2	3	Dragon, Young Green	Type:Dragon:Green");
addPawn("BS1	172	large	1	7	1	3	Dragon, Young Red	Type:Dragon:Red");
addPawn("BS1	173	large	1	8	5	1	Dragon, Young Silver	Type:Dragon:Silver");
addPawn("BS1	174	large	1	8	4	1	Drider	Type:Humanoid:Elf:Drow:Drider, Type:Beast:Insect:Arachnid");
addPawn("BS1	175	large	1	8	3	1	Duergar (enlarged)	Type:Humanoid:Dwarf:Duergar");
addPawn("BS1	176	large	1	8	2	1	Elemental, Air	Type:Elemental:Air");
addPawn("BS1	177	large	1	8	1	1	Elemental, Earth	Type:Elemental:Earth");
addPawn("BS1	178	large	1	8	5	2	Elemental, Fire	Type:Elemental:Fire");
addPawn("BS1	179	large	1	8	4	2	Elemental, Water	Type:Elemental:Water");
addPawn("BS1	180	large	1	8	3	2	Ettin	Type:Humanoid:Giant:Ettin");
addPawn("BS1	181	large	1	8	2	2	Gelatinous Cube	Type:Weird:Ooze");
addPawn("BS1	182	large	1	8	1	2	Genie, Djinni	Type:Humanoid:Genie, Type:Elemental:Air");
addPawn("BS1	183	large	1	8	5	3	Genie, Efreeti	Type:Humanoid:Genie, Type:Elemental:Fire");
addPawn("BS1	184	large	1	8	4	3	Genie, Marid	Type:Humanoid:Genie, Type:Elemental:Water");
addPawn("BS1	185	large	1	8	3	3	Genie, Shaitan	Type:Humanoid:Genie, Type:Elemental:Earth");
addPawn("BS1	186	large	1	8	2	3	Giant, Fire	Type:Humanoid:Giant:Fire");
addPawn("BS1	187	large	1	8	1	3	Giant, Frost	Type:Humanoid:Giant:Frost");
addPawn("BS1	188	large	1	9	5	1	Giant, Hill	Type:Humanoid:Giant:Hill");
addPawn("BS1	189	large	1	9	4	1	Giant, Stone	Type:Humanoid:Giant:Stone");
addPawn("BS1	190	large	1	9	3	1	Girallon	Type:Beast:Bipedal");
addPawn("BS1	191	large	1	9	2	1	Golem, Clay	Type:Golem:Clay");
addPawn("BS1	192	large	1	9	1	1	Golem, Flesh	Type:Golem:Flesh");
addPawn("BS1	193	large	1	9	5	2	Golem, Iron	Type:Golem:Iron");
addPawn("BS1	194	large	1	9	4	2	Golem, Stone	Type:Golem:Stone");
addPawn("BS1	195	large	1	9	3	2	Gorgon	Type:Beast:Quadrupedal");
addPawn("BS1	196	large	1	9	2	2	Griffon	Type:Beast:Quadrupedal:Griffon");
addPawn("BS1	197	large	1	9	1	2	Half-Celestial Unicorn	Type:Beast:Quadrupedal:Horse:Pegasus");
addPawn("BS1	198	large	1	9	5	3	Half-Fiend Minotaur	Type:Humanoid:Minotaur, Type:Outsider:Evil:Demon");
addPawn("BS1	199	large	1	9	4	3	Herd Animal, Aurochs	Type:Animal:Quadrupedal:Aurochs");
addPawn("BS1	200	large	1	9	3	3	Herd Animal, Bison	Type:Animal:Quadrupedal:Bison");
addPawn("BS1	201	large	1	9	2	3	Horse	Type:Animal:Quadrupedal:Horse, Misc:Mount");
addPawn("BS1	202	large	1	9	1	3	Lamia	Type:Humanoid:Centaur");
addPawn("BS1	203	large	1	10	5	1	Lion	Type:Animal:Quadrupedal:Lion");
addPawn("BS1	204	large	1	10	4	1	Lizard, Giant Frilled	Type:Animal:Quadrupedal:Lizard");
addPawn("BS1	205	large	1	10	3	1	Manticore	Type:Beast:Quadrupedal:Manticore");
addPawn("BS1	206	large	1	10	2	1	Mantis, Giant	Type:Animal:Insect:Mantis");
addPawn("BS1	207	large	1	10	1	1	Minotaur	Type:Humanoid:Minotaur");
addPawn("BS1	208	large	1	10	5	2	Naga, Dark	Type:Beast:Serpent:Naga");
addPawn("BS1	209	large	1	10	4	2	Naga, Guardian	Type:Beast:Serpent:Naga");
addPawn("BS1	210	large	1	10	3	2	Naga, Spirit	Type:Beast:Serpent:Naga");
addPawn("BS1	211	large	1	10	2	2	Nightmare	Type:Beast:Quadrupedal:Horse:Nightmare");
addPawn("BS1	212	large	1	10	1	2	Ochre Jelly	Type:Weird:Ooze");
addPawn("BS1	213	large	2	10	5	3	Ogre	Type:Humanoid:Ogre");
addPawn("BS1	214	large	1	10	3	3	Oni, Ogre Mage	Type:Humanoid:Ogre");
addPawn("BS1	215	large	1	10	2	3	Otyugh	Type:Weird:Aberration");
addPawn("BS1	216	large	1	10	1	3	Owlbear	Type:Beast:Quadrupedal:Owlbear");
addPawn("BS1	217	large	1	11	5	1	Pegasus	Type:Beast:Quadrupedal:Horse:Pegasus");
addPawn("BS1	218	large	1	11	4	1	Phase Spider	Type:Beast:Insect:Arachnid");
addPawn("BS1	219	large	1	11	3	1	Rhinoceros, Woolly	Type:Animal:Quadrupedal:Rhinoceros");
addPawn("BS1	220	large	1	11	2	1	Roper	Type:Weird:Aberration");
addPawn("BS1	221	large	1	11	1	1	Scorpion, Giant	Type:Animal:Insect:Scorpion");
addPawn("BS1	222	large	1	11	5	2	Shambling Mound	Type:Weird:Plant");
addPawn("BS1	223	large	1	11	4	2	Shark	Type:Animal:Aquatic:Shark, Environment:Aquatic");
addPawn("BS1	224	large	1	11	3	2	Sphinx, Gynosphinx	Type:Beast:Quadrupedal:Sphinx");
addPawn("BS1	225	large	1	11	2	2	Tiger, Dire	Type:Animal:Quadrupedal:Cat:Tiger");
addPawn("BS1	226	large	1	11	1	2	Troll	Type:Humanoid:Troll");
addPawn("BS1	227	large	1	11	5	3	Unicorn	Type:Beast:Quadrupedal:Horse:Unicorn");
addPawn("BS1	228	large	1	11	4	3	Wasp, Giant	Type:Animal:Insect:Wasp");
addPawn("BS1	229	large	1	11	3	3	Wolf, Dire	Type:Animal:Quadrupedal:Dog:Wolf");
addPawn("BS1	230	large	1	11	2	3	Wyvern	Type:Dragon:Dragonkin:Wyvern");
addPawn("BS1	231	large	1	11	1	3	Yeti	Type:Humanoid:Giant:Yeti, Environment:Arctic");
addPawn("BS1	232	huge	1	12	3	1	Aboleth	Type:Weird:Aberration:Aquatic, Environment:Aquatic");
addPawn("BS1	233	huge	1	12	2	1	Bebilith	Type:Outsider:Evil:Arachnid, Type:Beast:Insect:Arachnid");
addPawn("BS1	234	huge	1	12	1	1	Behir	Type:Dragon:Dragonkin, Type:Beast:Serpent");
addPawn("BS1	235	huge	1	12	2	2	Black Pudding	Type:Weird:Ooze");
addPawn("BS1	236	huge	1	12	1	2	Bulette	Type:Beast:Quadrupedal");
addPawn("BS1	237	huge	1	13	3	1	Demon, Glabrezu	Type:Outsider:Evil:Demon");
addPawn("BS1	238	huge	1	13	2	1	Demon, Nalfeshnee	Type:Outsider:Evil:Demon");
addPawn("BS1	239	huge	1	13	1	1	Dragon, Adult Blue	Type:Dragon:Blue");
addPawn("BS1	240	huge	1	13	2	2	Dragon, Adult Green	Type:Dragon:Green");
addPawn("BS1	241	huge	1	13	1	2	Dragon, Adult Red	Type:Dragon:Red");
addPawn("BS1	242	huge	1	14	3	1	Dragon, Ancient Black	Type:Dragon:Black");
addPawn("BS1	243	huge	1	14	2	1	Dragon, Ancient White	Type:Dragon:White");
addPawn("BS1	244	huge	1	14	1	1	Dragon Turtle	Type:Animal:Aquatic:Turtle");
addPawn("BS1	245	huge	1	14	2	2	Elephant, Mastodon	Type:Animal:Quadrupedal:Elephant");
addPawn("BS1	246	huge	1	14	1	2	Flytrap, Giant	Type:Weird:Plant:Carnivorous");
addPawn("BS1	247	huge	1	15	3	1	Froghemoth	Type:Weird:Aberration:Aquatic, Environment:Aquatic");
addPawn("BS1	248	huge	1	15	2	1	Giant, Cloud	Type:Humanoid:Giant:Cloud");
addPawn("BS1	249	huge	1	15	1	1	Giant, Storm	Type:Humanoid:Giant:Storm");
addPawn("BS1	250	huge	1	15	2	2	Hydra	Type:Beast:Serpent");
addPawn("BS1	251	huge	1	15	1	2	Remorhaz	Type:Beast:Worm, Environment:Arctic");
addPawn("BS1	252	huge	1	16	3	1	Retriever	Type:Animal:Insect:Spider");
addPawn("BS1	253	huge	1	16	2	1	Shoggoth	Type:Weird:Aberration, Type:Weird:Ooze");
addPawn("BS1	254	huge	1	16	1	1	Slug, Giant	Type:Animal:Insect:Slug");
addPawn("BS1	255	huge	1	16	2	2	Squid, Giant	Type:Animal:Aquatic:Octopus, Environment:Aquatic");
addPawn("BS1	256	huge	1	16	1	2	Treant	Type:Weird:Plant:Humanoid");
addPawn("BS2	1	small	1	0	0	0	Aeon, Paracletus	Type:Outsider:Neutral");
addPawn("BS2	2	small	1	0	0	0	Agathion, Vulpinal	Type:Humanoid:Type:Animal:Fox");
addPawn("BS2	3	small	1	0	0	0	Angel, Cassisian	Type:Outsider:Good:Angel");
addPawn("BS2	4	small	1	0	0	0	Attic Whisperer	Type:Humanoid:Kobold, Type:Undead:Corporeal:Skeleton");
addPawn("BS2	5	small	1	0	0	0	Aurumvorax	Type:Animal:Quadrupedal:Cat, Type:Beast:Quadrupedal");
addPawn("BS2	6	small	1	0	0	0	Badger	Type:Animal:Quadrupedal:Badger");
addPawn("BS2	7	small	1	0	0	0	Blindheim	Type:Outsider:Evil");
addPawn("BS2	8	small	1	0	0	0	Charda	Type:Outsider:Evil");
addPawn("BS2	9	small	1	0	0	0	Chupacabra	Type:Beast:Bipedal");
addPawn("BS2	10	small	1	0	0	0	Cockroach, Giant	Type:Animal:Insect:Cockroach");
addPawn("BS2	11	small	1	0	0	0	Crysmal	Type:Animal:Insect:Scorpion, Type:Elemental:Crystal");
addPawn("BS2	12	small	1	0	0	0	Dark Slayer	Type:Humanoid:Gnome, Misc:Class:Mage");
addPawn("BS2	13	small	1	0	0	0	Devil, Accuser	Type:Outsider:Evil");
addPawn("BS2	14	small	1	0	0	0	Elemental, Ice	Type:Elemental:Ice");
addPawn("BS2	15	small	1	0	0	0	Elemental, Lightning	Type:Elemental:Lightning");
addPawn("BS2	16	small	1	0	0	0	Elemental, Magma	Type:Elemental:Magma");
addPawn("BS2	17	small	1	0	0	0	Elemental, Mud	Type:Elemental:Mud");
addPawn("BS2	18	small	1	0	0	0	Fungal Crawler	Type:Animal:Insect");
addPawn("BS2	19	small	1	0	0	0	Gremlin, Nuglub	Type:Outsider:Evil");
addPawn("BS2	20	small	1	0	0	0	Grindylow	Type:Humanoid:Goblin:Aquatic");
addPawn("BS2	21	small	1	0	0	0	Grippli	Type:Humanoid:Type:Animal:Aquatic:Frog");
addPawn("BS2	22	small	1	0	0	0	Gryph	Type:Animal:Flying:Bird");
addPawn("BS2	23	small	1	0	0	0	Korred	Type:Humanoid:Gnome");
addPawn("BS2	24	small	1	0	0	0	Leprechaun	Type:Fae:Leprechaun");
addPawn("BS2	25	small	1	0	0	0	Lurker in Light	Type:Fae:Faerie");
addPawn("BS2	26	small	1	0	0	0	Mandragora	Type:Weird:Plant:Humanoid");
addPawn("BS2	27	small	1	0	0	0	Pech	Type:Humanoid:Gnome");
addPawn("BS2	28	small	1	0	0	0	Phycomid	Type:Weird:Plant:Fungus");
addPawn("BS2	29	small	1	0	0	0	Quickling	Type:Fae:Quickling");
addPawn("BS2	30	small	1	0	0	0	Redcap	Type:Fae:Redcap, Type:Humanoid:Gnome");
addPawn("BS2	31	small	1	0	0	0	Reefclaw	Type:Beast:Serpent, Environment:Aquatic");
addPawn("BS2	32	small	1	0	0	0	Slithering Tracker	Type:Weird:Ooze");
addPawn("BS2	33	small	1	0	0	0	Spriggan	Type:Fae:Spriggan");
addPawn("BS2	34	small	1	0	0	0	Tick, Giant	Type:Animal:Insect:Tick");
addPawn("BS2	35	small	1	0	0	0	Xtabay	Type:Weird:Plant");
addPawn("BS2	36	small	4	0	0	0	Amoeba Swarm	Type:Weird:Ooze, Misc:Swarm");
addPawn("BS2	37	small	4	0	0	0	Cockroach Swarm	Type:Animal:Insect:Cockroach, Misc:Swarm");
addPawn("BS2	38	small	4	0	0	0	Jellyfish Swarm	Type:Animal:Aquatic:Jellyfish, Misc:Swarm");
addPawn("BS2	39	small	4	0	0	0	Mosquito Swarm	Type:Animal:Insect:Mosquito, Misc:Swarm");
addPawn("BS2	40	small	4	0	0	0	Tick Swarm	Type:Animal:Insect:Tick, Misc:Swarm");
addPawn("BS2	41	medium	1	0	0	0	Aeon, Akhana	Type:Weird:Eye, Misc:Familiar, Type:Weird:Aberration");
addPawn("BS2	42	medium	1	0	0	0	Aeon, Theletos	Type:Weird:Aberration, Type:Beast:Worm");
addPawn("BS2	43	medium	1	0	0	0	Agathion, Avoral	Type:Humanoid:Bird:Harpy");
addPawn("BS2	44	medium	1	0	0	0	Agathion, Cetaceal	Type:Humanoid:Mermaid, Environment:Aquatic");
addPawn("BS2	45	medium	1	0	0	0	Agathion, Leonal	Type:Humanoid:Leonin, Type:Animal:Quadrupedal:Cat");
addPawn("BS2	46	medium	2	0	0	0	Akata	Type:Weird:Aberration, Type:Beast:Quadrupedal");
addPawn("BS2	47	medium	1	0	0	0	Angel, Monadic Deva	Type:Outsider:Good:Angel");
addPawn("BS2	48	medium	1	0	0	0	Angel, Movanic Deva	Type:Outsider:Good:Angel");
addPawn("BS2	49	medium	1	0	0	0	Animate Dream	Type:Animal:Quadrupedal:Horse, Type:Weird:Shapeshifter");
addPawn("BS2	50	medium	1	0	0	0	Aranea	Type:Animal:Insect:Spider");
addPawn("BS2	51	medium	2	0	0	0	Axiomite	Type:Humanoid:Elf, Misc:Civilian:Blacksmith");
addPawn("BS2	52	medium	1	0	0	0	Azata, Brijidine	Type:Humanoid:Misc, Type:Elemental:Fire");
addPawn("BS2	53	medium	2	0	0	0	Azer	Type:Elemental:Fire, Type:Humanoid:Dwarf");
addPawn("BS2	54	medium	1	0	0	0	Badger, Dire	Type:Animal:Quadrupedal:Badger");
addPawn("BS2	55	medium	1	0	0	0	Banshee	Type:Undead:Incorporeal:Banshee");
addPawn("BS2	56	medium	3	0	0	0	Bee, Giant	Type:Animal:Insect:Bee");
addPawn("BS2	57	medium	1	0	0	0	Blink Dog	Type:Outsider:Good, Type:Animal:Quadrupedal:Dog");
addPawn("BS2	58	medium	1	0	0	0	Bodak	Type:Undead:Corporeal:Zombie");
addPawn("BS2	59	medium	1	0	0	0	Bunyip	Type:Animal:Aquatic:Seal, Environment:Aquatic");
addPawn("BS2	60	medium	1	0	0	0	Chaos Beast	Type:Weird:Aberration");
addPawn("BS2	61	medium	2	0	0	0	Crawling Hand, Giant	Type:Undead:Corporeal:Piecemeal");
addPawn("BS2	62	medium	1	0	0	0	Crypt Thing	Type:Undead:Corporeal:Skeleton:Lich, Misc:Class:Mage");
addPawn("BS2	63	medium	2	0	0	0	D'ziriak	Type:Humanoid:Insect");
addPawn("BS2	64	medium	1	0	0	0	Daemon, Piscodaemon	Type:Outsider:Evil, Environment:Aquatic");
addPawn("BS2	65	medium	1	0	0	0	Daemon, Thanadaemon	Type:Elemental:Shadow, Type:Undead:Corporeal:Skeleton");
addPawn("BS2	66	medium	1	0	0	0	Decapus	Type:Weird:Aberration, Type:Animal:Aquatic:Octopus");
addPawn("BS2	67	medium	1	0	0	0	Demon, Kalavakus	Type:Outsider:Evil:Demon, Type:Humanoid:Minotaur");
addPawn("BS2	68	medium	1	0	0	0	Demon, Omox	Type:Outsider:Evil, Type:Elemental:Shadow");
addPawn("BS2	69	medium	3	0	0	0	Denizen of Leng	Type:Humanoid:Human, Environment:Desert");
addPawn("BS2	70	medium	1	0	0	0	Devil, Handmaiden	Type:Outsider:Evil");
addPawn("BS2	71	medium	2	0	0	0	Dhampir	Type:Humanoid:Elf:Drow");
addPawn("BS2	72	medium	1	0	0	0	Dragon, Young Brine	Type:Dragon:Brine, Environment:Aquatic");
addPawn("BS2	73	medium	1	0	0	0	Dragon, Young Crystal	Type:Dragon:Crystal");
addPawn("BS2	74	medium	1	0	0	0	Dragon, Young Magma	Type:Dragon:Magma");
addPawn("BS2	75	medium	1	0	0	0	Dragonfly, Giant	Type:Animal:Insect:Dragonfly");
addPawn("BS2	76	medium	3	0	0	0	Draugr	Type:Undead:Corporeal:Zombie");
addPawn("BS2	77	medium	1	0	0	0	Dullahan	Type:Humanoid, Misc:Class:Rogue:Assassin");
addPawn("BS2	78	medium	1	0	0	0	Elemental, Ice	Type:Elemental:Ice");
addPawn("BS2	79	medium	1	0	0	0	Elemental, Lightning	Type:Elemental:Lightning");
addPawn("BS2	80	medium	1	0	0	0	Elemental, Magma	Type:Elemental:Magma");
addPawn("BS2	81	medium	1	0	0	0	Elemental, Mud	Type:Elemental:Mud");
addPawn("BS2	82	medium	2	0	0	0	Faceless Stalker	Type:Weird:Aberration");
addPawn("BS2	83	medium	2	0	0	0	Fetchling	Type:Humanoid, Misc:Class:Rogue");
addPawn("BS2	84	medium	1	0	0	0	Fly, Giant	Type:Animal:Insect:Fly");
addPawn("BS2	85	medium	1	0	0	0	Fly, Giant Maggot	Type:Animal:Insect:Maggot");
addPawn("BS2	86	medium	2	0	0	0	Forlarren	Type:Fae:Satyr");
addPawn("BS2	87	medium	1	0	0	0	Gar	Type:Animal:Aquatic:Gar, Environment:Aquatic");
addPawn("BS2	88	medium	1	0	0	0	Golem, Carrion	Type:Golem:Flesh, Type:Undead:Corporeal:Zombie");
addPawn("BS2	89	medium	3	0	0	0	Grick	Type:Weird:Aberration, Type:Beast:Worm");
addPawn("BS2	90	medium	1	0	0	0	Herd Animal, Ram	Type:Animal:Quadrupedal:Ram");
addPawn("BS2	91	medium	1	0	0	0	Hound of Tindalos	Type:Weird:Aberration, Type:Beast:Quadrupedal");
addPawn("BS2	92	medium	2	0	0	0	Ifrit	Type:Humanoid:Elemental, Type:Elemental:Fire");
addPawn("BS2	93	medium	1	0	0	0	Inevitable, Kolyarut	Type:Humanoid:Warforged, Type:Outsider:Lawful");
addPawn("BS2	94	medium	1	0	0	0	Jellyfish, Crimson	Type:Animal:Aquatic:Jellyfish, Environment:Aquatic");
addPawn("BS2	95	medium	2	0	0	0	Jyoti	Type:Humanoid:Bird:Aven");
addPawn("BS2	96	medium	1	0	0	0	Kelpie	Type:Fae:Kelpie, Environment:Aquatic");
addPawn("BS2	97	medium	3	0	0	0	Krenshar	Type:Beast:Quadrupedal, Type:Animal:Quadrupedal:Cat");
addPawn("BS2	98	medium	2	0	0	0	Locathah	Type:Humanoid:Fish, Environment:Aquatic");
addPawn("BS2	99	medium	1	0	0	0	Lycanthrope, Werebear	Type:Humanoid:Lycanthrope:Werebear, Type:Animal:Quadrupedal:Bear");
addPawn("BS2	100	medium	1	0	0	0	Lycanthrope, Wereboar	Type:Humanoid:Lycanthrope:Wereboar, Type:Animal:Quadrupedal:Boar");
addPawn("BS2	101	medium	1	0	0	0	Lycanthrope, Weretiger	Type:Humanoid:Lycanthrope:Weretiger, Type:Animal:Quadrupedal:Cat:Tiger");
addPawn("BS2	102	medium	1	0	0	0	Mihstu	Type:Elemental:Air, Type:Undead:Incorporeal");
addPawn("BS2	103	medium	3	0	0	0	Mongrelman	Type:Weird:Aberration:Humanoid, Type:Outsider:Evil");
addPawn("BS2	104	medium	1	0	0	0	Mosquito, Giant	Type:Animal:Insect:Mosquito");
addPawn("BS2	105	medium	1	0	0	0	Mothman	Type:Outsider:Evil");
addPawn("BS2	106	medium	1	0	0	0	Necrophidius	Type:Animal:Snake, Type:Undead:Corporeal:Piecemeal");
addPawn("BS2	107	medium	2	0	0	0	Nereid	Type:Fae:Nereid");
addPawn("BS2	108	medium	3	0	0	0	Ogrekin	Type:Humanoid:Ogre");
addPawn("BS2	109	medium	2	0	0	0	Oread	Type:Humanoid:Elf:Drow");
addPawn("BS2	110	medium	1	0	0	0	Peryton	Type:Outsider:Evil:Demon");
addPawn("BS2	111	medium	1	0	0	0	Petitioner	Type:Elemental:Shadow, Type:Undead:Incorporeal:Shade");
addPawn("BS2	112	medium	1	0	0	0	Poltergeist	Type:Undead:Corporeal:Skeleton:Lich");
addPawn("BS2	113	medium	1	0	0	0	Qlippoth, Nyogoth	Type:Weird:Aberration");
addPawn("BS2	114	medium	3	0	0	0	Rast	Type:Weird:Aberration");
addPawn("BS2	115	medium	1	0	0	0	Ray, Stingray	Type:Animal:Aquatic:Ray, Environment:Aquatic");
addPawn("BS2	116	medium	1	0	0	0	Revenant	Type:Undead:Incorporeal:Ghost");
addPawn("BS2	117	medium	1	0	0	0	Sandman	Type:Humanoid:Elemental, Type:Elemental:Sand");
addPawn("BS2	118	medium	2	0	0	0	Scarecrow	Type:Outsider:Evil");
addPawn("BS2	119	medium	2	0	0	0	Sceaduinar	Type:Outsider:Evil:Imp");
addPawn("BS2	120	medium	1	0	0	0	Scorpion, Cave	Type:Animal:Insect:Scorpion");
addPawn("BS2	121	medium	3	0	0	0	Serpentfolk	Type:Humanoid:Reptillian:Serpent, Misc:Class:Mage");
addPawn("BS2	122	medium	2	0	0	0	Shining Child	Type:Undead:Corporeal:Zombie, Type:Outsider:Neutral");
addPawn("BS2	123	medium	3	0	0	0	Sinspawn	Type:Undead:Corporeal:Ghoul");
addPawn("BS2	124	medium	1	0	0	0	Siren	Type:Humanoid:Bird:Harpy");
addPawn("BS2	125	medium	2	0	0	0	Skulk	Type:Elemental:Shadow");
addPawn("BS2	126	medium	1	0	0	0	Slurk	Type:Animal:Aquatic:Frog");
addPawn("BS2	127	medium	1	0	0	0	Solifugid, Albino Cave	Type:Animal:Insect:Scorpion");
addPawn("BS2	128	medium	1	0	0	0	Soul Eater	Type:Undead:Incorporeal:Shade");
addPawn("BS2	129	medium	2	0	0	0	Sylph	Type:Fae:Sylph");
addPawn("BS2	130	medium	1	0	0	0	Tenebrous Worm	Type:Animal:Insect:Centipede");
addPawn("BS2	131	medium	1	0	0	0	Tentamort	Type:Weird:Aberration, Type:Animal:Aquatic:Squid, Environment:Underground");
addPawn("BS2	132	medium	2	0	0	0	Thoqqua	Type:Beast:Worm, Type:Elemental:Fire");
addPawn("BS2	133	medium	2	0	0	0	Totenmaske	Type:Outsider:Evil");
addPawn("BS2	134	medium	2	0	0	0	Triton	Type:Humanoid:Merfolk, Environment:Aquatic");
addPawn("BS2	135	medium	2	0	0	0	Undine	Type:Humanoid:Merfolk, Environment:Aquatic");
addPawn("BS2	136	medium	2	0	0	0	Urdefhan	Type:Undead:Corporeal:Ghoul");
addPawn("BS2	137	medium	1	0	0	0	Vampiric Mist	Type:Undead:Incorporeal:Shade");
addPawn("BS2	138	medium	1	0	0	0	Winterwight	Type:Undead:Corporeal:Skeleton");
addPawn("BS2	139	medium	2	0	0	0	Witchfire	Type:Undead:Incorporeal:Shade");
addPawn("BS2	140	medium	2	0	0	0	Witchwyrd	Type:Outsider:Evil, Misc:Class:Cleric:Evil");
addPawn("BS2	141	medium	1	0	0	0	Worm That Walks	Type:Outsider:Evil");
addPawn("BS2	142	medium	3	0	0	0	Zombie, Juju	Type:Undead:Corporeal:Ghoul");
addPawn("BS2	143	large	1	0	0	0	Achaierai	Type:Weird:Aberration, Type:Undead:Incorporeal:Shade, Type:Elemental:Shadow, Type:Beast:Quadrupedal:Bird");
addPawn("BS2	144	large	1	0	0	0	Aeon, Bythos	Type:Elemental:Air, Type:Humanoid:Elemental");
addPawn("BS2	145	large	1	0	0	0	Aeon, Pleroma	Type:Outsider:Neutral");
addPawn("BS2	146	large	1	0	0	0	Agathion, Draconal	Type:Humanoid:Reptillian:Draconic");
addPawn("BS2	147	large	1	0	0	0	Amphisbaena	Type:Animal:Snake, Type:Beast:Serpent");
addPawn("BS2	148	large	1	0	0	0	Archon, Shield	Type:Outsider:Good:Archon, Type:Humanoid:Giant");
addPawn("BS2	149	large	1	0	0	0	Archon, Star	Type:Outsider:Good:Archon");
addPawn("BS2	150	large	2	0	0	0	Bat, Mobat	Type:Animal:Flying:Bat");
addPawn("BS2	151	large	1	0	0	0	Bat, Skaveling	Type:Undead:Corporeal:Zombie:Animal, Type:Animal:Flying:Bat");
addPawn("BS2	152	large	1	0	0	0	Belker	Type:Elemental:Air, Type:Undead:Incorporeal:Shade, Type:Elemental:Shadow");
addPawn("BS2	153	large	1	0	0	0	Catoblepas	Type:Beast:Quadrupedal, Type:Beast:Quadrupedal:Pig");
addPawn("BS2	154	large	1	0	0	0	Daemon, Astradaemon	Type:Outsider:Evil");
addPawn("BS2	155	large	1	0	0	0	Daemon, Ceustodaemon	Type:Outsider:Evil:Demon, Type:Humanoid:Minotaur");
addPawn("BS2	156	large	1	0	0	0	Daemon, Derghodaemon	Type:Outsider:Evil, Type:Animal:Insect:Spider");
addPawn("BS2	157	large	1	0	0	0	Daemon, Hydrodaemon	Type:Animal:Aquatic:Frog, Type:Outsider:Evil");
addPawn("BS2	158	large	1	0	0	0	Daemon, Leukodaemon	Type:Outsider:Evil:Demon");
addPawn("BS2	159	large	1	0	0	0	Daemon, Meladaemon	Type:Outsider:Evil:Demon, Type:Humanoid:Gnoll");
addPawn("BS2	160	large	1	0	0	0	Daemon, Purrodaemon	Type:Outsider:Evil");
addPawn("BS2	161	large	1	0	0	0	Death Worm	Type:Beast:Worm, Type:Animal:Snake");
addPawn("BS2	162	large	1	0	0	0	Demon, Vrolikai	Type:Outsider:Evil:Demon, Type:Weird:Gargoyle");
addPawn("BS2	163	large	1	0	0	0	Destrachan	Type:Beast:Bipedal");
addPawn("BS2	164	large	1	0	0	0	Devil, Belier	Type:Outsider:Evil");
addPawn("BS2	165	large	1	0	0	0	Devil, Immolation	Type:Outsider:Evil:Devil");
addPawn("BS2	166	large	2	0	0	0	Devilfish	Type:Animal:Aquatic:Octopus, Environment:Aquatic");
addPawn("BS2	167	large	1	0	0	0	Dragon Horse	Type:Animal:Quadrupedal:Horse, Type:Beast:Quadrupedal:Horse:Nightmare");
addPawn("BS2	168	large	1	0	0	0	Dragon, Adult Brine	Type:Dragon:Brine, Environment:Aquatic");
addPawn("BS2	169	large	1	0	0	0	Dragon, Adult Crystal	Type:Dragon:Crystal");
addPawn("BS2	170	large	1	0	0	0	Dragon, Adult Magma	Type:Dragon:Magma");
addPawn("BS2	171	large	1	0	0	0	Dragon, Young Cloud	Type:Dragon:Cloud");
addPawn("BS2	172	large	1	0	0	0	Dragon, Young Umbral	Type:Dragon:Umbral");
addPawn("BS2	173	large	1	0	0	0	Drake, Flame	Type:Dragon:Dragonkin:Drake:Flame");
addPawn("BS2	174	large	1	0	0	0	Drake, Forest	Type:Dragon:Dragonkin:Drake:Forest");
addPawn("BS2	175	large	1	0	0	0	Drake, Frost	Type:Dragon:Dragonkin:Drake:Frost");
addPawn("BS2	176	large	1	0	0	0	Drake, Sea	Type:Dragon:Dragonkin:Drake:Sea, Environment:Aquatic");
addPawn("BS2	177	large	1	0	0	0	Dust Digger	Type:Beast:Insect, Type:Weird:Tentacles");
addPawn("BS2	178	large	1	0	0	0	Elemental, Ice	Type:Elemental:Ice");
addPawn("BS2	179	large	1	0	0	0	Elemental, Lightning	Type:Elemental:Lightning");
addPawn("BS2	180	large	1	0	0	0	Elemental, Magma	Type:Elemental:Magma");
addPawn("BS2	181	large	1	0	0	0	Elemental, Mud	Type:Elemental:Mud");
addPawn("BS2	182	large	2	0	0	0	Giant, Marsh	Type:Humanoid:Giant, Environment:Aquatic");
addPawn("BS2	183	large	2	0	0	0	Giant, Wood	Type:Humanoid:Giant");
addPawn("BS2	184	large	1	0	0	0	Gloomwing	Type:Animal:Insect:Moth");
addPawn("BS2	185	large	1	0	0	0	Golem, Alchemical	Type:Golem:Alchemical");
addPawn("BS2	186	large	1	0	0	0	Golem, Clockwork	Type:Golem:Clockwork");
addPawn("BS2	187	large	1	0	0	0	Golem, Glass	Type:Golem:Glass");
addPawn("BS2	188	large	1	0	0	0	Gray Render	Type:Humanoid:Giant");
addPawn("BS2	189	large	2	0	0	0	Gug	Type:Humanoid:Bestial");
addPawn("BS2	190	large	2	0	0	0	Hellcat	Type:Animal:Quadrupedal:Cat, Type:Elemental:Fire, Type:Outsider:Evil");
addPawn("BS2	191	large	1	0	0	0	Herd Animal, Camel	Type:Animal:Quadrupedal:Camel, Misc:Mount, Type:Humanoid:Human");
addPawn("BS2	192	large	1	0	0	0	Hippocampus	Type:Beast:Quadrupedal:Horse, Misc:Mount, Environment:Aquatic");
addPawn("BS2	193	large	2	0	0	0	Hippogriff	Type:Beast:Quadrupedal:Griffon, Misc:Mount");
addPawn("BS2	194	large	1	0	0	0	Hippopotamus	Type:Animal:Aquatic:Hippopotamus");
addPawn("BS2	195	large	2	0	0	0	Howler	Type:Animal:Quadrupedal:Cat, Type:Beast:Quadrupedal:Cat");
addPawn("BS2	196	large	1	0	0	0	Inevitable, Marut	Type:Outsider:Lawful, Type:Humanoid:Giant");
addPawn("BS2	197	large	1	0	0	0	Inevitable, Zelekhut	Type:Humanoid:Centaur, Type:Outsider:Lawful");
addPawn("BS2	198	large	1	0	0	0	Jellyfish, Giant	Type:Animal:Aquatic:Jellyfish");
addPawn("BS2	199	large	1	0	0	0	Lamia Matriarch	Type:Humanoid:Reptillian:Serpent");
addPawn("BS2	200	large	2	0	0	0	Leucrotta	Type:Beast:Quadrupedal");
addPawn("BS2	201	large	1	0	0	0	Magma Ooze	Type:Weird:Ooze, Type:Elemental:Magma");
addPawn("BS2	202	large	1	0	0	0	Mercane	Type:Humanoid:Giant");
addPawn("BS2	203	large	2	0	0	0	Merrow	Type:Humanoid:Giant:Merfolk, Environment:Aquatic");
addPawn("BS2	204	large	1	0	0	0	Neh-Thalggu	Type:Weird:Aberration:Arachnid");
addPawn("BS2	205	large	1	0	0	0	Protean, Imentesh	Type:Humanoid:Reptillian:Serpent");
addPawn("BS2	206	large	1	0	0	0	Protean, Keketar	Type:Humanoid:Reptillian:Serpent");
addPawn("BS2	207	large	1	0	0	0	Protean, Naunet	Type:Humanoid:Reptillian:Serpent");
addPawn("BS2	208	large	1	0	0	0	Qlippoth, Chernobue	Type:Weird:Aberration:Eye, Environment:Aquatic");
addPawn("BS2	209	large	1	0	0	0	Qlippoth, Shoggti	Type:Animal:Aquatic:Octopus, Environment:Aquatic");
addPawn("BS2	210	large	1	0	0	0	Qlippoth, Thulgant	Type:Outsider:Neutral, Type:Animal:Insect:Spider");
addPawn("BS2	211	large	1	0	0	0	Ray, Manta	Type:Animal:Aquatic:Ray");
addPawn("BS2	212	large	1	0	0	0	Seugathi	Type:Beast:Worm");
addPawn("BS2	213	large	1	0	0	0	Slime Mold	Type:Weird:Plant");
addPawn("BS2	214	large	1	0	0	0	Snake, Emperor Cobra	Type:Animal:Snake");
addPawn("BS2	215	large	2	0	0	0	Spider, Giant Black Widow	Type:Animal:Insect:Spider");
addPawn("BS2	216	large	1	0	0	0	Spriggan, Large	Type:Fae:Spriggan");
addPawn("BS2	217	large	2	0	0	0	Toad, Giant	Type:Animal:Aquatic:Frog");
addPawn("BS2	218	large	3	0	0	0	Troll, Ice	Type:Humanoid:Troll:Ice");
addPawn("BS2	219	large	3	0	0	0	Troll, Rock	Type:Humanoid:Troll:Rock");
addPawn("BS2	220	large	1	0	0	0	Viper Vine	Type:Weird:Plant");
addPawn("BS2	221	large	1	0	0	0	Wendigo	Type:Outsider:Neutral");
addPawn("BS2	222	huge	1	0	0	0	Athach	Type:Humanoid:Giant");
addPawn("BS2	223	huge	1	0	0	0	Dragon, Adult Cloud	Type:Dragon:Cloud");
addPawn("BS2	224	huge	1	0	0	0	Dragon, Adult Umbral	Type:Dragon:Umbral");
addPawn("BS2	225	huge	1	0	0	0	Dragon, Ancient Brine	Type:Dragon:Brine, Environment:Aquatic");
addPawn("BS2	226	huge	1	0	0	0	Dragon, Ancient Crystal	Type:Dragon:Crystal");
addPawn("BS2	227	huge	1	0	0	0	Dragon, Ancient Magma	Type:Dragon:Magma");
addPawn("BS2	228	huge	1	0	0	0	Frost Worm	Type:Beast:Worm, Environment:Arctic");
addPawn("BS2	229	huge	1	0	0	0	Giant, Taiga	Type:Humanoid:Giant:Taiga");
addPawn("BS2	230	huge	1	0	0	0	Golem, Adamantine	Type:Golem:Metal:Adamantine");
addPawn("BS2	231	huge	1	0	0	0	Golem, Mithral	Type:Golem:Metal:Mithral, Type:Weird:Shapeshifter, Type:Weird:Ooze");
addPawn("BS2	232	huge	1	0	0	0	Hangman Tree	Type:Weird:Plant");
addPawn("BS2	233	huge	1	0	0	0	Inevitable, Lhaksharut	Type:Outsider:Lawful");
addPawn("BS2	234	huge	1	0	0	0	Jabberwock	Type:Dragon:Dragonkin");
addPawn("BS2	235	huge	1	0	0	0	Leng Spider	Type:Animal:Insect:Spider");
addPawn("BS2	236	huge	1	0	0	0	Moonflower	Type:Weird:Plant:Carnivorous");
addPawn("BS2	237	huge	1	0	0	0	Nightshade, Nightwalker	Type:Outsider:Evil:Devil");
addPawn("BS2	238	huge	1	0	0	0	Nightshade, Nightwing	Type:Outsider:Evil, Type:Elemental:Shadow");
addPawn("BS2	239	huge	1	0	0	0	Qlippoth, Augnagar	Type:Outsider:Evil:Arachnid");
addPawn("BS2	240	huge	1	0	0	0	Quickwood	Type:Weird:Plant");
addPawn("BS2	241	huge	1	0	0	0	Scylla	Type:Outsider:Evil");
addPawn("BS2	242	huge	1	0	0	0	Shantak	Type:Dragon:Dragonkin");
addPawn("BS2	243	huge	1	0	0	0	Tendriculos	Type:Weird:Plant");
addPawn("BS2	244	huge	1	0	0	0	Thrasfyr	Type:Outsider:Evil:Devil");
addPawn("BS2	245	huge	1	0	0	0	Vemerak	Type:Outsider:Evil:Arachnid");
addPawn("BS2	246	huge	1	0	0	0	Water Orm	Type:Dragon:Dragonkin, Type:Beast:Aquatic, Environment:Aquatic");